### ISSUE TITLE
Uploading audio file via curl produces an error.

### ISSUE THREAD

**Issue by darnn** [arihanv/Shush#2]
Hi. I'm afraid I'm a complete novice when it comes to coding, so the process of getting this up and running was pretty laborious.
I tried the method described on the main GitHub page, using Bun, and eventually got the frontend running on http://localhost:3000/tryit. However, it doesn't display the server information from Modal. With your sample site, it looks like this:
![image](https://github.com/arihanv/Shush/assets/19672444/498b9a0e-f812-4bab-b2df-9d34ee19856e)
Whereas mine looks like this:
![image](https://github.com/arihanv/Shush/assets/19672444/a439c2dd-d623-47c2-82e0-492d42cf001d)
And when I try to send the file regardless, I get a "failed to send file" error. That's neither here nor there, though, that's all just to say that that made me go try the second method, the one described [here](https://shush.arihanv.com/) as "deploy on Modal".
When I get to the curl portion, if I use the following command:
`curl -i -X POST -H "Content-Type: application/octet-stream" --data-binary @"D:\ac3.mp3" "https://<modal_org_name>--whisper-v3-entrypoint.modal.run?audio=ac3.mp3`
after the file is uploaded, I get the following error in Modal itself:

Traceback (most recent call last):
  File "/pkg/modal/_container_entrypoint.py", line 342, in handle_input_exception
    yield
  File "/pkg/modal/_container_entrypoint.py", line 460, in run_inputs
    res = imp_fun.fun(*args, **kwargs)
  File "/root/modal_app.py", line 77, in generate
    output = self.pipe(
  File "/usr/local/lib/python3.9/site-packages/transformers/pipelines/automatic_speech_recognition.py", line 357, in __call__
    return super().__call__(inputs, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/transformers/pipelines/base.py", line 1132, in __call__
    return next(
  File "/usr/local/lib/python3.9/site-packages/transformers/pipelines/pt_utils.py", line 124, in __next__
    item = next(self.iterator)
  File "/usr/local/lib/python3.9/site-packages/transformers/pipelines/pt_utils.py", line 266, in __next__
    processed = self.infer(next(self.iterator), **self.params)
  File "/usr/local/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 630, in __next__
    data = self._next_data()
  File "/usr/local/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 674, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/usr/local/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 32, in fetch
    data.append(next(self.dataset_iter))
  File "/usr/local/lib/python3.9/site-packages/transformers/pipelines/pt_utils.py", line 183, in __next__
    processed = next(self.subiterator)
  File "/usr/local/lib/python3.9/site-packages/transformers/pipelines/automatic_speech_recognition.py", line 434, in preprocess
    inputs = ffmpeg_read(inputs, self.feature_extractor.sampling_rate)
  File "/usr/local/lib/python3.9/site-packages/transformers/pipelines/audio_utils.py", line 41, in ffmpeg_read
    raise ValueError(
ValueError: Soundfile is either not in the correct format or is malformed. Ensure that the soundfile has a valid audio file extension (e.g. wav, flac or mp3) and is not corrupted. If reading from a remote URL, ensure that the URL is the full address to **download** the audio file.

And Modal does process the same file using your sample site.

**Comment by darnn** [comment]
No no, the file does work on your site, which is why I mentioned it. Also, I changed the URL in .env.example and renamed it .env, and then tried to run the local frontend again, but there was no change.

**Comment by arihanv** [comment]
Hey @darnn . #4 should have resolved the issue with the audio file not reading correctly. The code in [modal_app.py](https://github.com/arihanv/Shush/blob/main/modal/modal_app.py) has been updated with fixes. Below are the new commands to make a curl request.

Deploy the new code:
`modal deploy modal_app.py`

Make curl request:
`curl -X POST -F "audio=@<file>" https://<org_name>--whisper-v3-demo-entrypoint.modal.run`

Let me know if this fixes the issue!
